name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  ci_part:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
           cd signature-rest
           docker-compose stop
           git pull https://github.com/id000000369/signature-rest.git
           npm run build
           docker-compose up -d
           cd
           
      - name: Happy Message for CI finish
        run: echo "CI Pipeline part Finished successfully!"

  cd_part:
    runs-on: ubuntu-latest
    needs: [ci_part]
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
           cd ../../var/www
           rm -rf build
           cd 
           cd signature-rest
           mv build ../../var/www
           nginx -s reload
           
      - name: Print Happy Message for CD finish
        run: echo "CD Pipeline part Finished successfully!"
