name: CI-CD-Pipeline-via-SSH

on:
  push:
    branches:
      - master

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Create ZIP deployment package
        run: zip -r signature_app_${{ github.sha }}.zip ./ -x *.git*

      - name: Print Happy Message for CI finish
        run: echo "Commit Pipeline part Finished successfully!"
