name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SERVER_PRIVATE_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Deploy
      - run: ssh -i "$HOME/.ssh/key" -o StrictHostKeyChecking=no root@89.147.109.197 "mkdir -p /root/prod"
      - name: Deploy via SCP
      - run: scp -i "$HOME/.ssh/key" -o StrictHostKeyChecking=no -r . root@89.147.109.197:/root/prod

       

